# Generated by Django 4.1.7 on 2023-11-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=500)),
                ('contact', models.CharField(max_length=300)),
            ],
        ),
    ]
